# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'modern_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(957, 510)
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon-96.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QLabel{\n"
"    color: white;\n"
"    font: 9pt \"JetBrains Mono\";\n"
"}\n"
"QGroupBox{\n"
"    border: 0px;\n"
"}\n"
"QGroupBox::title{\n"
"    color: gray;\n"
"}\n"
"\n"
"QPushButton{\n"
"    \n"
"    font: 9pt \"JetBrains Mono\";\n"
"    border: 0px;\n"
"    color:white;\n"
"}\n"
"QPushButton::hover{\n"
"    color: gray;\n"
"}\n"
"\n"
"QLineEdit{\n"
"    padding-left: 2px;\n"
"    color: white;\n"
"    border: 2px solid rgb(17, 17, 21);\n"
"    border-radius: 3px;\n"
"    font: 9pt \"JetBrains Mono\";\n"
"    background-color: rgb(17, 17, 21);\n"
"}\n"
"QLineEdit::hover{\n"
"    border-color: #539dd8;\n"
"}\n"
"QLineEdit::focus {\n"
"    border-color: #539dd8;\n"
"}\n"
"\n"
"QSpinBox{\n"
"    padding-left: 2px;\n"
"    color: white;\n"
"    border: 2px solid rgb(17, 17, 21);\n"
"    border-radius: 3px;\n"
"    font: 9pt \"JetBrains Mono\";\n"
"}\n"
"\n"
"QSpinBox::hover{\n"
"    border-color: #539dd8;\n"
"}\n"
"\n"
"QSpinBox::focus{border-color: rgb(0, 85, 255);}\n"
"\n"
"QSpinBox::up-arrow { height: 0px; width: 0px; border-left: 10px solid none; border-right: 10px solid none; border-bottom: 27px solid white;  }\n"
"QSpinBox::down-arrow{ height: 0px; width: 0px; border-left: 9px solid none; border-right: 9px solid none;  border-top: 28px solid white;}\n"
"QSpinBox::up-arrow::hover { height: 0px; width: 0px; border-left: 10px solid none; border-right: 10px solid none; border-bottom: 27px solid white }\n"
"QSpinBox::down-arrow::hover{ height: 0px; width: 0px; border-left: 9px solid none; border-right: 9px solid none;  border-top: 28px solid white;}\n"
"QSpinBox::up-arrow::focus { height: 0px; width: 0px; border-left: 10px solid none; border-right: 10px solid none; border-bottom: 27px solid white }\n"
"QSpinBox::down-arrow::focus{ height: 0px; width: 0px; border-left: 9px solid none; border-right: 9px solid none;  border-top: 28px solid white;}\n"
"\n"
"\n"
"QDoubleSpinBox{\n"
"    padding-left: 2px;\n"
"    color: white;\n"
"    border: 2px solid rgb(17, 17, 21);\n"
"    border-radius: 3px;\n"
"    font: 9pt \"JetBrains Mono\";\n"
"}\n"
"\n"
"QDoubleSpinBox::hover{\n"
"    border-color: #539dd8;\n"
"}\n"
"\n"
"QDoubleSpinBox::focus{border-color: rgb(0, 85, 255);}\n"
"\n"
"QDoubleSpinBox::up-arrow { height: 0px; width: 0px; border-left: 10px solid none; border-right: 10px solid none; border-bottom: 27px solid white;  }\n"
"QDoubleSpinBox::down-arrow{ height: 0px; width: 0px; border-left: 9px solid none; border-right: 9px solid none;  border-top: 28px solid white;}\n"
"QDoubleSpinBox::up-arrow::hover { height: 0px; width: 0px; border-left: 10px solid none; border-right: 10px solid none; border-bottom: 27px solid white }\n"
"QDoubleSpinBox::down-arrow::hover{ height: 0px; width: 0px; border-left: 9px solid none; border-right: 9px solid none;  border-top: 28px solid white;}\n"
"QDoubleSpinBox::up-arrow::focus { height: 0px; width: 0px; border-left: 10px solid none; border-right: 10px solid none; border-bottom: 27px solid white }\n"
"QDoubleSpinBox::down-arrow::focus{ height: 0px; width: 0px; border-left: 9px solid none; border-right: 9px solid none;  border-top: 28px solid white;}\n"
"\n"
"\n"
"QComboBox{\n"
"    font: 9pt \"JetBrains Mono\";\n"
"    padding-left: 5px;\n"
"    color:white;\n"
"    border: 2px solid rgb(17, 17, 21);\n"
"    border-radius: 3px;\n"
"}\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 20px;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"QComboBox::hover{\n"
"    border-color: #539dd8;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    color: white;\n"
"    selection-background-color: rgb(29, 29, 36);\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"/*QComboBox QAbstractItemView::hover {\n"
"    border-left: 1px solid rgb(190, 190, 190);\n"
"\n"
"}*/\n"
"\n"
"QCheckBox{\n"
"    color: white;\n"
"    font: 9pt \"JetBrains Mono\";\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    height: 20px;\n"
"    width: 20px;\n"
"    background-color: #1b1c1f;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    color: rgb(17, 17, 21);\n"
"    background-color: #539dd8;\n"
"}\n"
"\n"
"QCheckBox::hover{\n"
"    border-color: #539dd8;\n"
"}\n"
"\n"
"QFrame{\n"
"background-color: rgb(17, 17, 21);\n"
"}\n"
"\n"
"QRadioButton{\n"
"color: white;\n"
"    font: 9pt \"JetBrains Mono\";\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    height: 16px;\n"
"    width: 16px;\n"
"    background-color: #1b1c1f;\n"
"    border: 1px solid rgb(17, 17, 21);\n"
"    border-radius: 15px;\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"    color: rgb(17, 17, 21);\n"
"    \n"
"    background-color: rgba(83, 157, 216, 250);\n"
"}\n"
"\n"
"Line{\n"
"    border: 0.5px solid white;\n"
"        border-style: inset;\n"
"}")
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.header2 = QtWidgets.QFrame(self.centralwidget)
        self.header2.setMaximumSize(QtCore.QSize(16777215, 45))
        self.header2.setStyleSheet("background-color: rgb(17, 17, 21);")
        self.header2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header2.setObjectName("header2")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.header2)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_2 = QtWidgets.QLabel(self.header2)
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setStyleSheet("\n"
"font: 81 10pt \"JetBrains Mono\";")
        self.label_2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setIndent(10)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_16.addWidget(self.label_2)
        self.gridLayout.addWidget(self.header2, 0, 0, 1, 1)
        self.side_bar = QtWidgets.QFrame(self.centralwidget)
        self.side_bar.setMinimumSize(QtCore.QSize(146, 0))
        self.side_bar.setMaximumSize(QtCore.QSize(136, 16777215))
        self.side_bar.setStyleSheet("#side_bar{\n"
"    \n"
"    background-color: rgb(17, 17, 21);\n"
"}")
        self.side_bar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.side_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.side_bar.setLineWidth(1)
        self.side_bar.setObjectName("side_bar")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.side_bar)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.side_bar)
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 55))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setContentsMargins(-1, 19, -1, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.main_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.main_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.main_btn.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.main_btn.setFont(font)
        self.main_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.main_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/button/icons/main-menu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.main_btn.setIcon(icon1)
        self.main_btn.setFlat(True)
        self.main_btn.setObjectName("main_btn")
        self.verticalLayout_4.addWidget(self.main_btn)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.botcontrol_btn = QtWidgets.QPushButton(self.side_bar)
        self.botcontrol_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.botcontrol_btn.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.botcontrol_btn.setFont(font)
        self.botcontrol_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botcontrol_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/button/icons/bot.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botcontrol_btn.setIcon(icon2)
        self.botcontrol_btn.setFlat(True)
        self.botcontrol_btn.setObjectName("botcontrol_btn")
        self.verticalLayout_2.addWidget(self.botcontrol_btn)
        self.groupBox = QtWidgets.QGroupBox(self.side_bar)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 127))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setContentsMargins(-1, 19, -1, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.joinleft_btn = QtWidgets.QPushButton(self.groupBox)
        self.joinleft_btn.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.joinleft_btn.setFont(font)
        self.joinleft_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.joinleft_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/button/icons/setting.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.joinleft_btn.setIcon(icon3)
        self.joinleft_btn.setFlat(True)
        self.joinleft_btn.setObjectName("joinleft_btn")
        self.verticalLayout_3.addWidget(self.joinleft_btn)
        self.spamjoin_btn = QtWidgets.QPushButton(self.groupBox)
        self.spamjoin_btn.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.spamjoin_btn.setFont(font)
        self.spamjoin_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.spamjoin_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.spamjoin_btn.setIcon(icon3)
        self.spamjoin_btn.setFlat(True)
        self.spamjoin_btn.setObjectName("spamjoin_btn")
        self.verticalLayout_3.addWidget(self.spamjoin_btn)
        self.spamchat_btn = QtWidgets.QPushButton(self.groupBox)
        self.spamchat_btn.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.spamchat_btn.setFont(font)
        self.spamchat_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.spamchat_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.spamchat_btn.setIcon(icon3)
        self.spamchat_btn.setFlat(True)
        self.spamchat_btn.setObjectName("spamchat_btn")
        self.verticalLayout_3.addWidget(self.spamchat_btn)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_3 = QtWidgets.QGroupBox(self.side_bar)
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setStyleSheet("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_10.setContentsMargins(-1, 19, -1, -1)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.about_btn = QtWidgets.QPushButton(self.groupBox_3)
        self.about_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.about_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/button/icons/info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.about_btn.setIcon(icon4)
        self.about_btn.setObjectName("about_btn")
        self.verticalLayout_10.addWidget(self.about_btn)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        spacerItem = QtWidgets.QSpacerItem(20, 265, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.frame_2 = QtWidgets.QFrame(self.side_bar)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_16 = QtWidgets.QLabel(self.frame_2)
        self.label_16.setMinimumSize(QtCore.QSize(70, 0))
        self.label_16.setIndent(-1)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_10.addWidget(self.label_16)
        self.botcount_lb = QtWidgets.QLabel(self.frame_2)
        self.botcount_lb.setObjectName("botcount_lb")
        self.horizontalLayout_10.addWidget(self.botcount_lb)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(self.side_bar)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_15 = QtWidgets.QLabel(self.frame)
        self.label_15.setMinimumSize(QtCore.QSize(70, 0))
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_9.addWidget(self.label_15)
        self.status_lb = QtWidgets.QLabel(self.frame)
        self.status_lb.setStyleSheet("color: rgb(255, 45, 3)")
        self.status_lb.setObjectName("status_lb")
        self.horizontalLayout_9.addWidget(self.status_lb)
        self.verticalLayout_2.addWidget(self.frame)
        self.gridLayout.addWidget(self.side_bar, 2, 0, 1, 1)
        self.content = QtWidgets.QFrame(self.centralwidget)
        self.content.setStyleSheet("background-color: rgb(22, 23, 29);")
        self.content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content.setObjectName("content")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.content)
        self.gridLayout_2.setContentsMargins(-1, -1, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_12 = QtWidgets.QFrame(self.content)
        self.frame_12.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_12.setMaximumSize(QtCore.QSize(20, 16777215))
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.sizegrip = QtWidgets.QFrame(self.frame_12)
        self.sizegrip.setGeometry(QtCore.QRect(47, 456, 14, 10))
        self.sizegrip.setMaximumSize(QtCore.QSize(14, 10))
        self.sizegrip.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sizegrip.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sizegrip.setObjectName("sizegrip")
        self.gridLayout_2.addWidget(self.frame_12, 0, 2, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(self.content)
        self.stackedWidget.setMinimumSize(QtCore.QSize(470, 0))
        self.stackedWidget.setStyleSheet("QStackedWidget::left-arrow{\n"
"\n"
"}")
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.stackedWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.stackedWidget.setLineWidth(0)
        self.stackedWidget.setMidLineWidth(0)
        self.stackedWidget.setObjectName("stackedWidget")
        self.main_page = QtWidgets.QWidget()
        self.main_page.setObjectName("main_page")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.main_page)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.annoying_gr = QtWidgets.QGroupBox(self.main_page)
        self.annoying_gr.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.annoying_gr.setFont(font)
        self.annoying_gr.setStyleSheet("#annoying_gr{\n"
"    background-color: rgb(17, 17, 21);\n"
"    border: 1px solid  rgb(17, 17, 21);\n"
"    border-radius: 15px;\n"
"}\n"
"#annoying_gr::title{\n"
"    color: rgb(255, 255, 255)\n"
"}")
        self.annoying_gr.setFlat(False)
        self.annoying_gr.setCheckable(False)
        self.annoying_gr.setObjectName("annoying_gr")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.annoying_gr)
        self.verticalLayout_5.setContentsMargins(-1, 19, -1, -1)
        self.verticalLayout_5.setSpacing(9)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_4 = QtWidgets.QFrame(self.annoying_gr)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 32))
        self.frame_4.setStyleSheet("background-color: rgb(17, 17, 21);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.frame_4)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.ip_tb = QtWidgets.QLineEdit(self.frame_4)
        self.ip_tb.setStyleSheet("background-color: rgb(22, 23, 29);")
        self.ip_tb.setClearButtonEnabled(False)
        self.ip_tb.setObjectName("ip_tb")
        self.horizontalLayout_3.addWidget(self.ip_tb)
        self.label_3 = QtWidgets.QLabel(self.frame_4)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.port_sp = QtWidgets.QSpinBox(self.frame_4)
        self.port_sp.setStyleSheet("background-color: rgb(22, 23, 29);")
        self.port_sp.setMaximum(65535)
        self.port_sp.setProperty("value", 0)
        self.port_sp.setObjectName("port_sp")
        self.horizontalLayout_3.addWidget(self.port_sp)
        self.verticalLayout_5.addWidget(self.frame_4)
        self.frame_8 = QtWidgets.QFrame(self.annoying_gr)
        self.frame_8.setStyleSheet("background-color: rgb(17, 17, 21);")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_6 = QtWidgets.QLabel(self.frame_8)
        self.label_6.setMaximumSize(QtCore.QSize(51, 16777215))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        self.name_path_tb = QtWidgets.QLineEdit(self.frame_8)
        self.name_path_tb.setStyleSheet("background-color: rgb(22, 23, 29);")
        self.name_path_tb.setClearButtonEnabled(False)
        self.name_path_tb.setObjectName("name_path_tb")
        self.horizontalLayout_8.addWidget(self.name_path_tb)
        self.browse_btn = QtWidgets.QPushButton(self.frame_8)
        self.browse_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.browse_btn.setStyleSheet("#browse_btn{\n"
"    border: 2px solid #16171D;\n"
"    border-radius: 3px;\n"
"    background-color: #16171D;\n"
"    font: 9pt \"JetBrains Mono\";\n"
"}\n"
"\n"
"#browse_btn::hover{\n"
"    border-color: #539dd8;\n"
"    margin-left: 0px;\n"
"    color: white;\n"
"    \n"
"    background-color: rgba(83, 157, 216, 50);\n"
"    \n"
"}")
        self.browse_btn.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/button/icons/folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.browse_btn.setIcon(icon5)
        self.browse_btn.setObjectName("browse_btn")
        self.horizontalLayout_8.addWidget(self.browse_btn)
        self.ran_name_cb = QtWidgets.QCheckBox(self.frame_8)
        self.ran_name_cb.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ran_name_cb.setChecked(True)
        self.ran_name_cb.setObjectName("ran_name_cb")
        self.horizontalLayout_8.addWidget(self.ran_name_cb)
        self.verticalLayout_5.addWidget(self.frame_8)
        self.frame_5 = QtWidgets.QFrame(self.annoying_gr)
        self.frame_5.setStyleSheet("background-color: rgb(17, 17, 21);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.frame_5)
        self.label_4.setMaximumSize(QtCore.QSize(51, 16777215))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.method_cb = QtWidgets.QComboBox(self.frame_5)
        self.method_cb.setMinimumSize(QtCore.QSize(0, 25))
        self.method_cb.setStyleSheet("background-color: rgb(22, 23, 29);")
        self.method_cb.setEditable(False)
        self.method_cb.setObjectName("method_cb")
        self.method_cb.addItem("")
        self.method_cb.addItem("")
        self.method_cb.addItem("")
        self.horizontalLayout_4.addWidget(self.method_cb)
        self.verticalLayout_5.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.annoying_gr)
        self.frame_6.setStyleSheet("background-color: rgb(17, 17, 21);")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.frame_6)
        self.label_5.setMaximumSize(QtCore.QSize(51, 16777215))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.ver_cb = QtWidgets.QComboBox(self.frame_6)
        self.ver_cb.setMinimumSize(QtCore.QSize(0, 25))
        self.ver_cb.setStyleSheet("background-color: rgb(22, 23, 29);")
        self.ver_cb.setEditable(False)
        self.ver_cb.setModelColumn(0)
        self.ver_cb.setObjectName("ver_cb")
        self.ver_cb.addItem("")
        self.ver_cb.addItem("")
        self.ver_cb.addItem("")
        self.ver_cb.addItem("")
        self.ver_cb.addItem("")
        self.ver_cb.addItem("")
        self.ver_cb.addItem("")
        self.ver_cb.addItem("")
        self.ver_cb.addItem("")
        self.ver_cb.addItem("")
        self.ver_cb.addItem("")
        self.ver_cb.addItem("")
        self.ver_cb.addItem("")
        self.ver_cb.addItem("")
        self.ver_cb.addItem("")
        self.ver_cb.addItem("")
        self.ver_cb.addItem("")
        self.ver_cb.addItem("")
        self.ver_cb.addItem("")
        self.ver_cb.addItem("")
        self.ver_cb.addItem("")
        self.ver_cb.addItem("")
        self.ver_cb.addItem("")
        self.ver_cb.addItem("")
        self.ver_cb.addItem("")
        self.ver_cb.addItem("")
        self.ver_cb.addItem("")
        self.ver_cb.addItem("")
        self.ver_cb.addItem("")
        self.ver_cb.addItem("")
        self.ver_cb.addItem("")
        self.horizontalLayout_5.addWidget(self.ver_cb)
        self.verticalLayout_5.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.annoying_gr)
        self.frame_7.setStyleSheet("background-color: rgb(17, 17, 21);")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.start_btn_2 = QtWidgets.QPushButton(self.frame_7)
        self.start_btn_2.setMinimumSize(QtCore.QSize(75, 30))
        self.start_btn_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.start_btn_2.setStyleSheet("#start_btn_2{\n"
"    /*border: 2px solid rgb(184, 184, 184);*/\n"
"    border-radius: 3px;\n"
"    \n"
"    font: 9pt \"JetBrains Mono\";\n"
"}\n"
"\n"
"#start_btn_2::hover{\n"
"    border-color:#539dd8;\n"
"    margin-left: 0px;\n"
"    color: white;\n"
"    \n"
"    background-color: rgba(83, 157, 216, 50);\n"
"    \n"
"}")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/button/icons/start.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.start_btn_2.setIcon(icon6)
        self.start_btn_2.setIconSize(QtCore.QSize(20, 20))
        self.start_btn_2.setObjectName("start_btn_2")
        self.horizontalLayout_6.addWidget(self.start_btn_2)
        self.stop_btn_2 = QtWidgets.QPushButton(self.frame_7)
        self.stop_btn_2.setMinimumSize(QtCore.QSize(75, 30))
        self.stop_btn_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.stop_btn_2.setStyleSheet("#stop_btn_2{\n"
"/*    border: 2px solid rgb(184, 184, 184);*/\n"
"    border-radius: 3px;\n"
"    \n"
"    font: 9pt \"JetBrains Mono\";\n"
"}\n"
"\n"
"#stop_btn_2::hover{\n"
"    border-color: #539dd8;\n"
"    margin-left: 0px;\n"
"    color: white;\n"
"    \n"
"    background-color: rgba(83, 157, 216, 50);\n"
"    \n"
"}")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/button/icons/stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stop_btn_2.setIcon(icon7)
        self.stop_btn_2.setIconSize(QtCore.QSize(25, 25))
        self.stop_btn_2.setObjectName("stop_btn_2")
        self.horizontalLayout_6.addWidget(self.stop_btn_2)
        self.kick_btn = QtWidgets.QPushButton(self.frame_7)
        self.kick_btn.setMinimumSize(QtCore.QSize(75, 30))
        self.kick_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.kick_btn.setStyleSheet("#kick_btn{\n"
"/*    border: 2px solid rgb(184, 184, 184);*/\n"
"    border-radius: 3px;\n"
"    \n"
"    font: 9pt \"JetBrains Mono\";\n"
"}\n"
"\n"
"#kick_btn::hover{\n"
"    border-color: #539dd8;\n"
"    margin-left: 0px;\n"
"    color: white;\n"
"    \n"
"    background-color: rgba(83, 157, 216, 50);\n"
"    \n"
"}")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/button/icons/kick.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.kick_btn.setIcon(icon8)
        self.kick_btn.setIconSize(QtCore.QSize(22, 22))
        self.kick_btn.setObjectName("kick_btn")
        self.horizontalLayout_6.addWidget(self.kick_btn)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.verticalLayout_5.addWidget(self.frame_7)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem3)
        self.horizontalLayout_2.addWidget(self.annoying_gr)
        self.frame_3 = QtWidgets.QFrame(self.main_page)
        self.frame_3.setMinimumSize(QtCore.QSize(42, 0))
        self.frame_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_6.setSpacing(16)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.annoying_gr_3 = QtWidgets.QGroupBox(self.frame_3)
        self.annoying_gr_3.setMinimumSize(QtCore.QSize(162, 0))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.annoying_gr_3.setFont(font)
        self.annoying_gr_3.setStyleSheet("#annoying_gr_3{\n"
"    background-color: rgb(17, 17, 21);\n"
"    border: 1px solid  rgb(17, 17, 21);\n"
"    border-radius: 15px;\n"
"}\n"
"#annoying_gr_3::title{\n"
"    color: rgb(255, 255, 255)\n"
"}\n"
"\n"
"QTableWidget{\n"
"    color: white;\n"
"    background-color: rgb(17, 17, 21);\n"
"}\n"
"\n"
"QHeaderView::section{\n"
"color:white;\n"
"background-color: rgb(17, 17, 21);\n"
"border: 1px solid  rgb(17, 17, 21);\n"
"\n"
"}\n"
"\n"
"")
        self.annoying_gr_3.setObjectName("annoying_gr_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.annoying_gr_3)
        self.horizontalLayout.setContentsMargins(-1, 18, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.botstatus = QtWidgets.QTableWidget(self.annoying_gr_3)
        self.botstatus.setMinimumSize(QtCore.QSize(0, 0))
        self.botstatus.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.botstatus.setStyleSheet("background-color: rgb(17, 17, 21);\n"
"border: 1px solid rgb(17, 17, 21);\n"
"border-radius: 20px;")
        self.botstatus.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.botstatus.setFrameShadow(QtWidgets.QFrame.Plain)
        self.botstatus.setLineWidth(1)
        self.botstatus.setAutoScrollMargin(10)
        self.botstatus.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.botstatus.setShowGrid(False)
        self.botstatus.setGridStyle(QtCore.Qt.NoPen)
        self.botstatus.setColumnCount(2)
        self.botstatus.setObjectName("botstatus")
        self.botstatus.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.botstatus.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.botstatus.setHorizontalHeaderItem(1, item)
        self.botstatus.horizontalHeader().setVisible(False)
        self.botstatus.horizontalHeader().setCascadingSectionResizes(False)
        self.botstatus.horizontalHeader().setHighlightSections(False)
        self.botstatus.horizontalHeader().setSortIndicatorShown(False)
        self.botstatus.horizontalHeader().setStretchLastSection(False)
        self.botstatus.verticalHeader().setVisible(False)
        self.botstatus.verticalHeader().setCascadingSectionResizes(False)
        self.botstatus.verticalHeader().setDefaultSectionSize(30)
        self.botstatus.verticalHeader().setMinimumSectionSize(23)
        self.botstatus.verticalHeader().setSortIndicatorShown(False)
        self.botstatus.verticalHeader().setStretchLastSection(False)
        self.horizontalLayout.addWidget(self.botstatus)
        self.verticalLayout_6.addWidget(self.annoying_gr_3)
        self.annoying_gr_2 = QtWidgets.QGroupBox(self.frame_3)
        self.annoying_gr_2.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.annoying_gr_2.setFont(font)
        self.annoying_gr_2.setStyleSheet("#annoying_gr_2{\n"
"    background-color: rgb(17, 17, 21);\n"
"    border: 1px solid  rgb(17, 17, 21);\n"
"    border-radius: 15px;\n"
"}\n"
"#annoying_gr_2::title{\n"
"    color: rgb(255, 255, 255);\n"
"\n"
"}")
        self.annoying_gr_2.setObjectName("annoying_gr_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.annoying_gr_2)
        self.gridLayout_6.setContentsMargins(19, 19, 19, 19)
        self.gridLayout_6.setHorizontalSpacing(7)
        self.gridLayout_6.setVerticalSpacing(9)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.log_tb = QtWidgets.QTextEdit(self.annoying_gr_2)
        self.log_tb.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.log_tb.setStyleSheet("color: white;\n"
"border: 1px solid rgb(17, 17, 21);\n"
"border-radius: 3px;")
        self.log_tb.setReadOnly(True)
        self.log_tb.setObjectName("log_tb")
        self.gridLayout_6.addWidget(self.log_tb, 0, 0, 1, 1)
        self.verticalLayout_6.addWidget(self.annoying_gr_2)
        self.horizontalLayout_2.addWidget(self.frame_3)
        self.stackedWidget.addWidget(self.main_page)
        self.joinleft_page = QtWidgets.QWidget()
        self.joinleft_page.setObjectName("joinleft_page")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.joinleft_page)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.joinleft_gr = QtWidgets.QGroupBox(self.joinleft_page)
        self.joinleft_gr.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.joinleft_gr.setFont(font)
        self.joinleft_gr.setStyleSheet("#joinleft_gr{\n"
"  background-color: rgb(17, 17, 21);\n"
"  border: 1px solid  rgb(17, 17, 21);\n"
"  border-radius: 15px;\n"
"}\n"
"#joinleft_gr::title{\n"
"  color: rgb(255, 255, 255)\n"
"}")
        self.joinleft_gr.setFlat(False)
        self.joinleft_gr.setCheckable(False)
        self.joinleft_gr.setObjectName("joinleft_gr")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.joinleft_gr)
        self.verticalLayout_7.setContentsMargins(-1, 19, -1, -1)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_9 = QtWidgets.QFrame(self.joinleft_gr)
        self.frame_9.setStyleSheet("background-color: rgb(17, 17, 21);")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_9)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_8 = QtWidgets.QLabel(self.frame_9)
        self.label_8.setObjectName("label_8")
        self.gridLayout_7.addWidget(self.label_8, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame_9)
        self.label_7.setObjectName("label_7")
        self.gridLayout_7.addWidget(self.label_7, 0, 0, 1, 1)
        self.delay_join1_sp = QtWidgets.QDoubleSpinBox(self.frame_9)
        self.delay_join1_sp.setMinimumSize(QtCore.QSize(310, 0))
        self.delay_join1_sp.setStyleSheet("background-color: rgb(22, 23, 29);")
        self.delay_join1_sp.setDecimals(1)
        self.delay_join1_sp.setMaximum(100.0)
        self.delay_join1_sp.setSingleStep(0.5)
        self.delay_join1_sp.setProperty("value", 1.0)
        self.delay_join1_sp.setObjectName("delay_join1_sp")
        self.gridLayout_7.addWidget(self.delay_join1_sp, 0, 1, 1, 1)
        self.delay_left_sp = QtWidgets.QDoubleSpinBox(self.frame_9)
        self.delay_left_sp.setStyleSheet("background-color: rgb(22, 23, 29);")
        self.delay_left_sp.setDecimals(1)
        self.delay_left_sp.setSingleStep(0.5)
        self.delay_left_sp.setProperty("value", 0.5)
        self.delay_left_sp.setObjectName("delay_left_sp")
        self.gridLayout_7.addWidget(self.delay_left_sp, 1, 1, 1, 1)
        self.verticalLayout_7.addWidget(self.frame_9)
        self.frame_13 = QtWidgets.QFrame(self.joinleft_gr)
        self.frame_13.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_13.setStyleSheet("background-color: rgb(17, 17, 21);")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_13)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_17 = QtWidgets.QLabel(self.frame_13)
        self.label_17.setMaximumSize(QtCore.QSize(96, 23456))
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_11.addWidget(self.label_17)
        self.left_after_login_rb = QtWidgets.QRadioButton(self.frame_13)
        self.left_after_login_rb.setChecked(True)
        self.left_after_login_rb.setObjectName("left_after_login_rb")
        self.horizontalLayout_11.addWidget(self.left_after_login_rb)
        self.line = QtWidgets.QFrame(self.frame_13)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_11.addWidget(self.line)
        self.left_after_spawn_rb = QtWidgets.QRadioButton(self.frame_13)
        self.left_after_spawn_rb.setStyleSheet("")
        self.left_after_spawn_rb.setObjectName("left_after_spawn_rb")
        self.horizontalLayout_11.addWidget(self.left_after_spawn_rb)
        self.verticalLayout_7.addWidget(self.frame_13)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem4)
        self.gridLayout_3.addWidget(self.joinleft_gr, 0, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem5, 0, 1, 1, 1)
        self.stackedWidget.addWidget(self.joinleft_page)
        self.spamjoin_page = QtWidgets.QWidget()
        self.spamjoin_page.setObjectName("spamjoin_page")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.spamjoin_page)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.spamjoin_gr = QtWidgets.QGroupBox(self.spamjoin_page)
        self.spamjoin_gr.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.spamjoin_gr.setFont(font)
        self.spamjoin_gr.setStyleSheet("#spamjoin_gr{\n"
"  background-color: rgb(17, 17, 21);\n"
"  border: 1px solid  rgb(17, 17, 21);\n"
"  border-radius: 15px;\n"
"}\n"
"#spamjoin_gr::title{\n"
"  color: rgb(255, 255, 255)\n"
"}")
        self.spamjoin_gr.setFlat(False)
        self.spamjoin_gr.setCheckable(False)
        self.spamjoin_gr.setObjectName("spamjoin_gr")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.spamjoin_gr)
        self.verticalLayout_8.setContentsMargins(-1, 19, -1, -1)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_10 = QtWidgets.QFrame(self.spamjoin_gr)
        self.frame_10.setStyleSheet("background-color: rgb(17, 17, 21);")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_10)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_9 = QtWidgets.QLabel(self.frame_10)
        self.label_9.setObjectName("label_9")
        self.gridLayout_8.addWidget(self.label_9, 0, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.frame_10)
        self.label_10.setObjectName("label_10")
        self.gridLayout_8.addWidget(self.label_10, 1, 0, 1, 1)
        self.maxbot_sp = QtWidgets.QSpinBox(self.frame_10)
        self.maxbot_sp.setMinimumSize(QtCore.QSize(310, 0))
        self.maxbot_sp.setStyleSheet("background-color: rgb(22, 23, 29);")
        self.maxbot_sp.setObjectName("maxbot_sp")
        self.gridLayout_8.addWidget(self.maxbot_sp, 0, 1, 1, 1)
        self.delay_join2_sp = QtWidgets.QDoubleSpinBox(self.frame_10)
        self.delay_join2_sp.setStyleSheet("background-color: rgb(22, 23, 29);")
        self.delay_join2_sp.setDecimals(1)
        self.delay_join2_sp.setMaximum(100.0)
        self.delay_join2_sp.setSingleStep(0.5)
        self.delay_join2_sp.setProperty("value", 1.0)
        self.delay_join2_sp.setObjectName("delay_join2_sp")
        self.gridLayout_8.addWidget(self.delay_join2_sp, 1, 1, 1, 1)
        self.verticalLayout_8.addWidget(self.frame_10)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem6)
        self.gridLayout_5.addWidget(self.spamjoin_gr, 0, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem7, 0, 1, 1, 1)
        self.stackedWidget.addWidget(self.spamjoin_page)
        self.spamchat_page = QtWidgets.QWidget()
        self.spamchat_page.setObjectName("spamchat_page")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.spamchat_page)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.spamchat_gr = QtWidgets.QGroupBox(self.spamchat_page)
        self.spamchat_gr.setMinimumSize(QtCore.QSize(426, 0))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.spamchat_gr.setFont(font)
        self.spamchat_gr.setStyleSheet("#spamchat_gr{\n"
"  background-color: rgb(17, 17, 21);\n"
"  border: 1px solid  rgb(17, 17, 21);\n"
"  border-radius: 15px;\n"
"}\n"
"#spamchat_gr::title{\n"
"  color: rgb(255, 255, 255)\n"
"}")
        self.spamchat_gr.setFlat(False)
        self.spamchat_gr.setCheckable(False)
        self.spamchat_gr.setObjectName("spamchat_gr")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.spamchat_gr)
        self.verticalLayout_9.setContentsMargins(-1, 19, -1, -1)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_11 = QtWidgets.QFrame(self.spamchat_gr)
        self.frame_11.setStyleSheet("background-color: rgb(17, 17, 21);")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame_11)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_11 = QtWidgets.QLabel(self.frame_11)
        self.label_11.setObjectName("label_11")
        self.gridLayout_9.addWidget(self.label_11, 1, 0, 1, 1)
        self.chat_tb = QtWidgets.QLineEdit(self.frame_11)
        self.chat_tb.setStyleSheet("background-color: rgb(22, 23, 29);")
        self.chat_tb.setObjectName("chat_tb")
        self.gridLayout_9.addWidget(self.chat_tb, 1, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.frame_11)
        self.label_12.setObjectName("label_12")
        self.gridLayout_9.addWidget(self.label_12, 2, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.frame_11)
        self.label_13.setObjectName("label_13")
        self.gridLayout_9.addWidget(self.label_13, 3, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.frame_11)
        self.label_14.setObjectName("label_14")
        self.gridLayout_9.addWidget(self.label_14, 0, 0, 1, 1)
        self.maxbot2_sp = QtWidgets.QSpinBox(self.frame_11)
        self.maxbot2_sp.setStyleSheet("background-color: rgb(22, 23, 29);")
        self.maxbot2_sp.setObjectName("maxbot2_sp")
        self.gridLayout_9.addWidget(self.maxbot2_sp, 0, 1, 1, 1)
        self.delay_chat_sp = QtWidgets.QDoubleSpinBox(self.frame_11)
        self.delay_chat_sp.setStyleSheet("background-color: rgb(22, 23, 29);")
        self.delay_chat_sp.setPrefix("")
        self.delay_chat_sp.setDecimals(1)
        self.delay_chat_sp.setMaximum(100.0)
        self.delay_chat_sp.setSingleStep(0.5)
        self.delay_chat_sp.setProperty("value", 0.5)
        self.delay_chat_sp.setObjectName("delay_chat_sp")
        self.gridLayout_9.addWidget(self.delay_chat_sp, 2, 1, 1, 1)
        self.delay_join3_sp = QtWidgets.QDoubleSpinBox(self.frame_11)
        self.delay_join3_sp.setStyleSheet("background-color: rgb(22, 23, 29);")
        self.delay_join3_sp.setDecimals(1)
        self.delay_join3_sp.setMaximum(100.0)
        self.delay_join3_sp.setSingleStep(0.5)
        self.delay_join3_sp.setProperty("value", 1.0)
        self.delay_join3_sp.setObjectName("delay_join3_sp")
        self.gridLayout_9.addWidget(self.delay_join3_sp, 3, 1, 1, 1)
        self.verticalLayout_9.addWidget(self.frame_11)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem8)
        self.gridLayout_4.addWidget(self.spamchat_gr, 0, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem9, 0, 1, 1, 1)
        self.stackedWidget.addWidget(self.spamchat_page)
        self.botcontrol_page = QtWidgets.QWidget()
        self.botcontrol_page.setObjectName("botcontrol_page")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.botcontrol_page)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.frame_17 = QtWidgets.QFrame(self.botcontrol_page)
        self.frame_17.setMaximumSize(QtCore.QSize(346783, 16777215))
        self.frame_17.setStyleSheet("")
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_17)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.groupBox_4 = QtWidgets.QGroupBox(self.frame_17)
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setStyleSheet("#groupBox_4{\n"
"    background-color: rgb(17, 17, 21);\n"
"    border: 1px solid  rgb(17, 17, 21);\n"
"    border-radius: 15px;\n"
"}\n"
"#groupBox_4::title{\n"
"    color: rgb(255, 255, 255);\n"
"\n"
"}")
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_11.setContentsMargins(-1, 19, -1, -1)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_15 = QtWidgets.QFrame(self.groupBox_4)
        self.frame_15.setMinimumSize(QtCore.QSize(0, 32))
        self.frame_15.setStyleSheet("background-color: rgb(17, 17, 21);")
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_19 = QtWidgets.QLabel(self.frame_15)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_13.addWidget(self.label_19)
        self.ip_tb_2 = QtWidgets.QLineEdit(self.frame_15)
        self.ip_tb_2.setStyleSheet("background-color: rgb(22, 23, 29);")
        self.ip_tb_2.setClearButtonEnabled(False)
        self.ip_tb_2.setObjectName("ip_tb_2")
        self.horizontalLayout_13.addWidget(self.ip_tb_2)
        self.label_20 = QtWidgets.QLabel(self.frame_15)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_13.addWidget(self.label_20)
        self.port_sp_2 = QtWidgets.QSpinBox(self.frame_15)
        self.port_sp_2.setStyleSheet("background-color: rgb(22, 23, 29);")
        self.port_sp_2.setMaximum(65535)
        self.port_sp_2.setProperty("value", 0)
        self.port_sp_2.setObjectName("port_sp_2")
        self.horizontalLayout_13.addWidget(self.port_sp_2)
        self.verticalLayout_11.addWidget(self.frame_15)
        self.frame_14 = QtWidgets.QFrame(self.groupBox_4)
        self.frame_14.setStyleSheet("background-color: rgb(17, 17, 21);")
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_18 = QtWidgets.QLabel(self.frame_14)
        self.label_18.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_12.addWidget(self.label_18)
        self.usrname_tb = QtWidgets.QLineEdit(self.frame_14)
        self.usrname_tb.setStyleSheet("background-color: rgb(22, 23, 29);")
        self.usrname_tb.setClearButtonEnabled(False)
        self.usrname_tb.setObjectName("usrname_tb")
        self.horizontalLayout_12.addWidget(self.usrname_tb)
        self.verticalLayout_11.addWidget(self.frame_14)
        self.frame_16 = QtWidgets.QFrame(self.groupBox_4)
        self.frame_16.setStyleSheet("background-color: rgb(17, 17, 21);")
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_16)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_21 = QtWidgets.QLabel(self.frame_16)
        self.label_21.setMaximumSize(QtCore.QSize(51, 16777215))
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_14.addWidget(self.label_21)
        self.ver_cb_2 = QtWidgets.QComboBox(self.frame_16)
        self.ver_cb_2.setMinimumSize(QtCore.QSize(0, 25))
        self.ver_cb_2.setStyleSheet("background-color: rgb(22, 23, 29);")
        self.ver_cb_2.setEditable(False)
        self.ver_cb_2.setModelColumn(0)
        self.ver_cb_2.setObjectName("ver_cb_2")
        self.ver_cb_2.addItem("")
        self.ver_cb_2.addItem("")
        self.ver_cb_2.addItem("")
        self.ver_cb_2.addItem("")
        self.ver_cb_2.addItem("")
        self.ver_cb_2.addItem("")
        self.ver_cb_2.addItem("")
        self.ver_cb_2.addItem("")
        self.ver_cb_2.addItem("")
        self.ver_cb_2.addItem("")
        self.ver_cb_2.addItem("")
        self.ver_cb_2.addItem("")
        self.ver_cb_2.addItem("")
        self.ver_cb_2.addItem("")
        self.ver_cb_2.addItem("")
        self.ver_cb_2.addItem("")
        self.ver_cb_2.addItem("")
        self.ver_cb_2.addItem("")
        self.ver_cb_2.addItem("")
        self.ver_cb_2.addItem("")
        self.ver_cb_2.addItem("")
        self.ver_cb_2.addItem("")
        self.ver_cb_2.addItem("")
        self.ver_cb_2.addItem("")
        self.ver_cb_2.addItem("")
        self.ver_cb_2.addItem("")
        self.ver_cb_2.addItem("")
        self.ver_cb_2.addItem("")
        self.ver_cb_2.addItem("")
        self.ver_cb_2.addItem("")
        self.ver_cb_2.addItem("")
        self.horizontalLayout_14.addWidget(self.ver_cb_2)
        self.verticalLayout_11.addWidget(self.frame_16)
        self.frame_20 = QtWidgets.QFrame(self.groupBox_4)
        self.frame_20.setStyleSheet("background-color: rgb(17, 17, 21);")
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.frame_20)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_22 = QtWidgets.QLabel(self.frame_20)
        self.label_22.setMaximumSize(QtCore.QSize(10000, 16777215))
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_18.addWidget(self.label_22)
        self.login_msg_tb = QtWidgets.QLineEdit(self.frame_20)
        self.login_msg_tb.setStyleSheet("background-color: rgb(22, 23, 29);")
        self.login_msg_tb.setClearButtonEnabled(False)
        self.login_msg_tb.setObjectName("login_msg_tb")
        self.horizontalLayout_18.addWidget(self.login_msg_tb)
        self.verticalLayout_11.addWidget(self.frame_20)
        self.frame_21 = QtWidgets.QFrame(self.groupBox_4)
        self.frame_21.setStyleSheet("background-color: rgb(17, 17, 21);")
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.frame_21)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_23 = QtWidgets.QLabel(self.frame_21)
        self.label_23.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_19.addWidget(self.label_23)
        self.left_msg_tb = QtWidgets.QLineEdit(self.frame_21)
        self.left_msg_tb.setStyleSheet("background-color: rgb(22, 23, 29);")
        self.left_msg_tb.setClearButtonEnabled(False)
        self.left_msg_tb.setObjectName("left_msg_tb")
        self.horizontalLayout_19.addWidget(self.left_msg_tb)
        self.verticalLayout_11.addWidget(self.frame_21)
        self.frame_18 = QtWidgets.QFrame(self.groupBox_4)
        self.frame_18.setMinimumSize(QtCore.QSize(0, 20))
        self.frame_18.setStyleSheet("background-color: rgb(17, 17, 21);")
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.frame_18)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem10)
        self.spawn_btn = QtWidgets.QPushButton(self.frame_18)
        self.spawn_btn.setMinimumSize(QtCore.QSize(75, 30))
        self.spawn_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.spawn_btn.setStyleSheet("#spawn_btn{\n"
"    /*border: 2px solid rgb(184, 184, 184);*/\n"
"    border-radius: 3px;\n"
"    \n"
"    font: 9pt \"JetBrains Mono\";\n"
"}\n"
"\n"
"#spawn_btn::hover{\n"
"    border-color:#539dd8;\n"
"    margin-left: 0px;\n"
"    color: white;\n"
"    \n"
"    background-color: rgba(83, 157, 216, 50);\n"
"    \n"
"}")
        self.spawn_btn.setIcon(icon6)
        self.spawn_btn.setIconSize(QtCore.QSize(20, 20))
        self.spawn_btn.setObjectName("spawn_btn")
        self.horizontalLayout_17.addWidget(self.spawn_btn)
        self.quit_btn = QtWidgets.QPushButton(self.frame_18)
        self.quit_btn.setMinimumSize(QtCore.QSize(75, 30))
        self.quit_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.quit_btn.setStyleSheet("#quit_btn{\n"
"/*    border: 2px solid rgb(184, 184, 184);*/\n"
"    border-radius: 3px;\n"
"    \n"
"    font: 9pt \"JetBrains Mono\";\n"
"}\n"
"\n"
"#quit_btn::hover{\n"
"    border-color: #539dd8;\n"
"    margin-left: 0px;\n"
"    color: white;\n"
"    \n"
"    background-color: rgba(83, 157, 216, 50);\n"
"    \n"
"}")
        self.quit_btn.setIcon(icon8)
        self.quit_btn.setIconSize(QtCore.QSize(22, 22))
        self.quit_btn.setObjectName("quit_btn")
        self.horizontalLayout_17.addWidget(self.quit_btn)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem11)
        self.verticalLayout_11.addWidget(self.frame_18)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem12)
        self.verticalLayout_13.addWidget(self.groupBox_4)
        self.horizontalLayout_15.addWidget(self.frame_17)
        self.frame_19 = QtWidgets.QFrame(self.botcontrol_page)
        self.frame_19.setMinimumSize(QtCore.QSize(30, 0))
        self.frame_19.setStyleSheet("#chatlog_gr{\n"
"    background-color: rgb(17, 17, 21);\n"
"    border: 1px solid  rgb(17, 17, 21);\n"
"    border-radius: 15px;\n"
"}\n"
"#chatlog_gr::title{\n"
"    color: rgb(255, 255, 255);\n"
"\n"
"}")
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_19)
        self.verticalLayout.setObjectName("verticalLayout")
        self.chatlog_gr = QtWidgets.QGroupBox(self.frame_19)
        self.chatlog_gr.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.chatlog_gr.setFont(font)
        self.chatlog_gr.setStyleSheet("#chatlog_gr{\n"
"    background-color: rgb(17, 17, 21);\n"
"    border: 1px solid  rgb(17, 17, 21);\n"
"    border-radius: 15px;\n"
"}\n"
"#chatlog_gr::title{\n"
"    color: rgb(255, 255, 255);\n"
"\n"
"}")
        self.chatlog_gr.setObjectName("chatlog_gr")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.chatlog_gr)
        self.gridLayout_11.setContentsMargins(19, 19, 19, 19)
        self.gridLayout_11.setHorizontalSpacing(7)
        self.gridLayout_11.setVerticalSpacing(9)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.chatlog_tb = QtWidgets.QTextEdit(self.chatlog_gr)
        self.chatlog_tb.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.chatlog_tb.setStyleSheet("color: white;\n"
"border: 1px solid rgb(17, 17, 21);\n"
"border-radius: 3px;")
        self.chatlog_tb.setReadOnly(True)
        self.chatlog_tb.setObjectName("chatlog_tb")
        self.gridLayout_11.addWidget(self.chatlog_tb, 0, 0, 1, 1)
        self.frame_22 = QtWidgets.QFrame(self.chatlog_gr)
        self.frame_22.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_22.setStyleSheet("background-color: rgb(17, 17, 21);")
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.frame_22)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.chat_tb_2 = QtWidgets.QLineEdit(self.frame_22)
        self.chat_tb_2.setMinimumSize(QtCore.QSize(0, 25))
        self.chat_tb_2.setMaximumSize(QtCore.QSize(325636, 16777215))
        self.chat_tb_2.setStyleSheet("background-color: rgb(22, 23, 29);")
        self.chat_tb_2.setClearButtonEnabled(False)
        self.chat_tb_2.setObjectName("chat_tb_2")
        self.horizontalLayout_20.addWidget(self.chat_tb_2)
        self.chat_btn = QtWidgets.QPushButton(self.frame_22)
        self.chat_btn.setMinimumSize(QtCore.QSize(75, 25))
        self.chat_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.chat_btn.setStyleSheet("#chat_btn{\n"
"    /*border: 2px solid rgb(184, 184, 184);*/\n"
"    border-radius: 3px;\n"
"    \n"
"    font: 9pt \"JetBrains Mono\";\n"
"}\n"
"\n"
"#chat_btn::hover{\n"
"    border-color:#539dd8;\n"
"    margin-left: 0px;\n"
"    color: white;\n"
"    \n"
"    background-color: rgba(83, 157, 216, 50);\n"
"    \n"
"}")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/button/icons/chat.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.chat_btn.setIcon(icon9)
        self.chat_btn.setIconSize(QtCore.QSize(20, 20))
        self.chat_btn.setObjectName("chat_btn")
        self.horizontalLayout_20.addWidget(self.chat_btn)
        self.gridLayout_11.addWidget(self.frame_22, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.chatlog_gr)
        self.logbot_gr = QtWidgets.QGroupBox(self.frame_19)
        self.logbot_gr.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.logbot_gr.setFont(font)
        self.logbot_gr.setStyleSheet("#logbot_gr{\n"
"    background-color: rgb(17, 17, 21);\n"
"    border: 1px solid  rgb(17, 17, 21);\n"
"    border-radius: 15px;\n"
"}\n"
"#logbot_gr::title{\n"
"    color: rgb(255, 255, 255);\n"
"\n"
"}")
        self.logbot_gr.setObjectName("logbot_gr")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.logbot_gr)
        self.gridLayout_13.setContentsMargins(19, 19, 19, 19)
        self.gridLayout_13.setHorizontalSpacing(7)
        self.gridLayout_13.setVerticalSpacing(9)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.logbot_tb = QtWidgets.QTextEdit(self.logbot_gr)
        self.logbot_tb.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.logbot_tb.setStyleSheet("color: white;\n"
"border: 1px solid rgb(17, 17, 21);\n"
"border-radius: 3px;")
        self.logbot_tb.setReadOnly(True)
        self.logbot_tb.setObjectName("logbot_tb")
        self.gridLayout_13.addWidget(self.logbot_tb, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.logbot_gr)
        self.horizontalLayout_15.addWidget(self.frame_19)
        self.stackedWidget.addWidget(self.botcontrol_page)
        self.gridLayout_2.addWidget(self.stackedWidget, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.content, 2, 1, 1, 1)
        self.header = QtWidgets.QFrame(self.centralwidget)
        self.header.setMaximumSize(QtCore.QSize(16777215, 45))
        self.header.setStyleSheet("background-color: rgb(17, 17, 21);")
        self.header.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header.setObjectName("header")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.header)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.start_btn = QtWidgets.QPushButton(self.header)
        self.start_btn.setMinimumSize(QtCore.QSize(35, 30))
        self.start_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.start_btn.setStyleSheet("#start_btn{\n"
"    /*border: 2px solid rgb(184, 184, 184);*/\n"
"    border-radius: 3px;\n"
"    \n"
"    font: 9pt \"JetBrains Mono\";\n"
"}\n"
"\n"
"#start_btn::hover{\n"
"    border-color:#539dd8;\n"
"    margin-left: 0px;\n"
"    color: white;\n"
"    \n"
"    background-color: rgba(83, 157, 216, 50);\n"
"    \n"
"}")
        self.start_btn.setText("")
        self.start_btn.setIcon(icon6)
        self.start_btn.setIconSize(QtCore.QSize(20, 20))
        self.start_btn.setObjectName("start_btn")
        self.horizontalLayout_7.addWidget(self.start_btn)
        self.stop_btn = QtWidgets.QPushButton(self.header)
        self.stop_btn.setMinimumSize(QtCore.QSize(35, 30))
        self.stop_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.stop_btn.setStyleSheet("#stop_btn{\n"
"/*    border: 2px solid rgb(184, 184, 184);*/\n"
"    border-radius: 3px;\n"
"    \n"
"    font: 9pt \"JetBrains Mono\";\n"
"}\n"
"\n"
"#stop_btn::hover{\n"
"    border-color: #539dd8;\n"
"    margin-left: 0px;\n"
"    color: white;\n"
"    \n"
"    background-color: rgba(83, 157, 216, 50);\n"
"    \n"
"}")
        self.stop_btn.setText("")
        self.stop_btn.setIcon(icon7)
        self.stop_btn.setIconSize(QtCore.QSize(25, 25))
        self.stop_btn.setObjectName("stop_btn")
        self.horizontalLayout_7.addWidget(self.stop_btn)
        self.kick_btn_2 = QtWidgets.QPushButton(self.header)
        self.kick_btn_2.setMinimumSize(QtCore.QSize(35, 30))
        self.kick_btn_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.kick_btn_2.setStyleSheet("#kick_btn_2{\n"
"/*    border: 2px solid rgb(184, 184, 184);*/\n"
"    border-radius: 3px;\n"
"    \n"
"    font: 9pt \"JetBrains Mono\";\n"
"}\n"
"\n"
"#kick_btn_2::hover{\n"
"    border-color: #539dd8;\n"
"    margin-left: 0px;\n"
"    color: white;\n"
"    \n"
"    background-color: rgba(83, 157, 216, 50);\n"
"    \n"
"}")
        self.kick_btn_2.setText("")
        self.kick_btn_2.setIcon(icon8)
        self.kick_btn_2.setIconSize(QtCore.QSize(22, 22))
        self.kick_btn_2.setObjectName("kick_btn_2")
        self.horizontalLayout_7.addWidget(self.kick_btn_2)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem13)
        self.mini_btn = QtWidgets.QPushButton(self.header)
        self.mini_btn.setMaximumSize(QtCore.QSize(12467, 1245))
        self.mini_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.mini_btn.setStyleSheet("#mini_btn::hover{\n"
"    margin-left: 0px;\n"
"}")
        self.mini_btn.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/button/icons/minimized.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mini_btn.setIcon(icon10)
        self.mini_btn.setIconSize(QtCore.QSize(14, 14))
        self.mini_btn.setObjectName("mini_btn")
        self.horizontalLayout_7.addWidget(self.mini_btn)
        self.max_btn = QtWidgets.QPushButton(self.header)
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(9)
        self.max_btn.setFont(font)
        self.max_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.max_btn.setStyleSheet("#max_btn::hover{\n"
"    margin-left: 0px;\n"
"}")
        self.max_btn.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/button/icons/maximized.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.max_btn.setIcon(icon11)
        self.max_btn.setIconSize(QtCore.QSize(14, 14))
        self.max_btn.setObjectName("max_btn")
        self.horizontalLayout_7.addWidget(self.max_btn)
        self.close_btn = QtWidgets.QPushButton(self.header)
        self.close_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.close_btn.setStyleSheet("#close_btn::hover{\n"
"    margin-left: 0px;\n"
"}")
        self.close_btn.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/button/icons/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close_btn.setIcon(icon12)
        self.close_btn.setIconSize(QtCore.QSize(14, 14))
        self.close_btn.setObjectName("close_btn")
        self.horizontalLayout_7.addWidget(self.close_btn)
        self.gridLayout.addWidget(self.header, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.ver_cb.setCurrentIndex(22)
        self.ver_cb_2.setCurrentIndex(22)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AnnoyingBot - v0.0.1"))
        self.label_2.setText(_translate("MainWindow", " ANNOYINGBOT "))
        self.groupBox_2.setTitle(_translate("MainWindow", "Main"))
        self.main_btn.setToolTip(_translate("MainWindow", "Main menu"))
        self.main_btn.setText(_translate("MainWindow", "Main"))
        self.botcontrol_btn.setToolTip(_translate("MainWindow", "Main menu"))
        self.botcontrol_btn.setText(_translate("MainWindow", "BotControl"))
        self.groupBox.setTitle(_translate("MainWindow", "Config"))
        self.joinleft_btn.setText(_translate("MainWindow", "JoinLeft"))
        self.spamjoin_btn.setText(_translate("MainWindow", "SpamJoin"))
        self.spamchat_btn.setText(_translate("MainWindow", "SpamChat"))
        self.groupBox_3.setTitle(_translate("MainWindow", "About"))
        self.about_btn.setToolTip(_translate("MainWindow", "About me and the project"))
        self.about_btn.setText(_translate("MainWindow", "About"))
        self.label_16.setToolTip(_translate("MainWindow", "Count bot started"))
        self.label_16.setText(_translate("MainWindow", "BotCount:"))
        self.botcount_lb.setToolTip(_translate("MainWindow", "Count bot started"))
        self.botcount_lb.setText(_translate("MainWindow", "0/0"))
        self.label_15.setText(_translate("MainWindow", "Status: "))
        self.status_lb.setText(_translate("MainWindow", "Off"))
        self.annoying_gr.setTitle(_translate("MainWindow", "Main"))
        self.label.setText(_translate("MainWindow", "IP"))
        self.label_3.setText(_translate("MainWindow", "Port"))
        self.label_6.setText(_translate("MainWindow", "Names"))
        self.ran_name_cb.setToolTip(_translate("MainWindow", "Generator name using uuid4"))
        self.ran_name_cb.setText(_translate("MainWindow", "Random"))
        self.label_4.setText(_translate("MainWindow", "Method"))
        self.method_cb.setItemText(0, _translate("MainWindow", "JoinLeft"))
        self.method_cb.setItemText(1, _translate("MainWindow", "SpamJoin"))
        self.method_cb.setItemText(2, _translate("MainWindow", "SpamChat"))
        self.label_5.setText(_translate("MainWindow", "Version"))
        self.ver_cb.setItemText(0, _translate("MainWindow", "1.8"))
        self.ver_cb.setItemText(1, _translate("MainWindow", "1.9"))
        self.ver_cb.setItemText(2, _translate("MainWindow", "1.10"))
        self.ver_cb.setItemText(3, _translate("MainWindow", "1.10.1"))
        self.ver_cb.setItemText(4, _translate("MainWindow", "1.10.2"))
        self.ver_cb.setItemText(5, _translate("MainWindow", "1.11"))
        self.ver_cb.setItemText(6, _translate("MainWindow", "1.11.2"))
        self.ver_cb.setItemText(7, _translate("MainWindow", "1.12"))
        self.ver_cb.setItemText(8, _translate("MainWindow", "1.12.1"))
        self.ver_cb.setItemText(9, _translate("MainWindow", "1.12.2"))
        self.ver_cb.setItemText(10, _translate("MainWindow", "1.13"))
        self.ver_cb.setItemText(11, _translate("MainWindow", "1.13.1"))
        self.ver_cb.setItemText(12, _translate("MainWindow", "1.13.2"))
        self.ver_cb.setItemText(13, _translate("MainWindow", "1.14"))
        self.ver_cb.setItemText(14, _translate("MainWindow", "1.14.1"))
        self.ver_cb.setItemText(15, _translate("MainWindow", "1.14.2"))
        self.ver_cb.setItemText(16, _translate("MainWindow", "1.15"))
        self.ver_cb.setItemText(17, _translate("MainWindow", "1.16"))
        self.ver_cb.setItemText(18, _translate("MainWindow", "1.16.1"))
        self.ver_cb.setItemText(19, _translate("MainWindow", "1.16.2"))
        self.ver_cb.setItemText(20, _translate("MainWindow", "1.16.3"))
        self.ver_cb.setItemText(21, _translate("MainWindow", "1.16.4"))
        self.ver_cb.setItemText(22, _translate("MainWindow", "1.16.5"))
        self.ver_cb.setItemText(23, _translate("MainWindow", "1.17"))
        self.ver_cb.setItemText(24, _translate("MainWindow", "1.17.1"))
        self.ver_cb.setItemText(25, _translate("MainWindow", "1.18"))
        self.ver_cb.setItemText(26, _translate("MainWindow", "1.18.1"))
        self.ver_cb.setItemText(27, _translate("MainWindow", "1.18.2"))
        self.ver_cb.setItemText(28, _translate("MainWindow", "1.19"))
        self.ver_cb.setItemText(29, _translate("MainWindow", "1.19.1"))
        self.ver_cb.setItemText(30, _translate("MainWindow", "1.19.2"))
        self.start_btn_2.setToolTip(_translate("MainWindow", "Start"))
        self.start_btn_2.setText(_translate("MainWindow", "Start"))
        self.stop_btn_2.setToolTip(_translate("MainWindow", "Stop"))
        self.stop_btn_2.setText(_translate("MainWindow", "Stop"))
        self.kick_btn.setToolTip(_translate("MainWindow", "Kick all bot in server"))
        self.kick_btn.setText(_translate("MainWindow", "Kick"))
        self.annoying_gr_3.setTitle(_translate("MainWindow", "BotStatus"))
        self.botstatus.setSortingEnabled(False)
        item = self.botstatus.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Bot"))
        item = self.botstatus.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Status"))
        self.annoying_gr_2.setTitle(_translate("MainWindow", "Log"))
        self.joinleft_gr.setTitle(_translate("MainWindow", "JoinLeft"))
        self.label_8.setText(_translate("MainWindow", "Delay Left"))
        self.label_7.setText(_translate("MainWindow", "Delay Join"))
        self.delay_join1_sp.setSuffix(_translate("MainWindow", "s"))
        self.delay_left_sp.setSuffix(_translate("MainWindow", "s"))
        self.label_17.setText(_translate("MainWindow", "Left Type"))
        self.left_after_login_rb.setText(_translate("MainWindow", "Left after login"))
        self.left_after_spawn_rb.setText(_translate("MainWindow", "Left after spawn"))
        self.spamjoin_gr.setTitle(_translate("MainWindow", "SpamJoin"))
        self.label_9.setText(_translate("MainWindow", "MaxBot"))
        self.label_10.setText(_translate("MainWindow", "Delay Join"))
        self.delay_join2_sp.setSuffix(_translate("MainWindow", "s"))
        self.spamchat_gr.setTitle(_translate("MainWindow", "SpamChat"))
        self.label_11.setText(_translate("MainWindow", "Chat"))
        self.chat_tb.setText(_translate("MainWindow", "Server Trash!"))
        self.label_12.setText(_translate("MainWindow", "Delay Chat"))
        self.label_13.setText(_translate("MainWindow", "Delay Join"))
        self.label_14.setText(_translate("MainWindow", "MaxBot"))
        self.delay_chat_sp.setSuffix(_translate("MainWindow", "s"))
        self.delay_join3_sp.setSuffix(_translate("MainWindow", "s"))
        self.groupBox_4.setTitle(_translate("MainWindow", "BotControl"))
        self.label_19.setText(_translate("MainWindow", "IP"))
        self.label_20.setText(_translate("MainWindow", "Port"))
        self.label_18.setText(_translate("MainWindow", "Username"))
        self.label_21.setText(_translate("MainWindow", "Version"))
        self.ver_cb_2.setItemText(0, _translate("MainWindow", "1.8"))
        self.ver_cb_2.setItemText(1, _translate("MainWindow", "1.9"))
        self.ver_cb_2.setItemText(2, _translate("MainWindow", "1.10"))
        self.ver_cb_2.setItemText(3, _translate("MainWindow", "1.10.1"))
        self.ver_cb_2.setItemText(4, _translate("MainWindow", "1.10.2"))
        self.ver_cb_2.setItemText(5, _translate("MainWindow", "1.11"))
        self.ver_cb_2.setItemText(6, _translate("MainWindow", "1.11.2"))
        self.ver_cb_2.setItemText(7, _translate("MainWindow", "1.12"))
        self.ver_cb_2.setItemText(8, _translate("MainWindow", "1.12.1"))
        self.ver_cb_2.setItemText(9, _translate("MainWindow", "1.12.2"))
        self.ver_cb_2.setItemText(10, _translate("MainWindow", "1.13"))
        self.ver_cb_2.setItemText(11, _translate("MainWindow", "1.13.1"))
        self.ver_cb_2.setItemText(12, _translate("MainWindow", "1.13.2"))
        self.ver_cb_2.setItemText(13, _translate("MainWindow", "1.14"))
        self.ver_cb_2.setItemText(14, _translate("MainWindow", "1.14.1"))
        self.ver_cb_2.setItemText(15, _translate("MainWindow", "1.14.2"))
        self.ver_cb_2.setItemText(16, _translate("MainWindow", "1.15"))
        self.ver_cb_2.setItemText(17, _translate("MainWindow", "1.16"))
        self.ver_cb_2.setItemText(18, _translate("MainWindow", "1.16.1"))
        self.ver_cb_2.setItemText(19, _translate("MainWindow", "1.16.2"))
        self.ver_cb_2.setItemText(20, _translate("MainWindow", "1.16.3"))
        self.ver_cb_2.setItemText(21, _translate("MainWindow", "1.16.4"))
        self.ver_cb_2.setItemText(22, _translate("MainWindow", "1.16.5"))
        self.ver_cb_2.setItemText(23, _translate("MainWindow", "1.17"))
        self.ver_cb_2.setItemText(24, _translate("MainWindow", "1.17.1"))
        self.ver_cb_2.setItemText(25, _translate("MainWindow", "1.18"))
        self.ver_cb_2.setItemText(26, _translate("MainWindow", "1.18.1"))
        self.ver_cb_2.setItemText(27, _translate("MainWindow", "1.18.2"))
        self.ver_cb_2.setItemText(28, _translate("MainWindow", "1.19"))
        self.ver_cb_2.setItemText(29, _translate("MainWindow", "1.19.1"))
        self.ver_cb_2.setItemText(30, _translate("MainWindow", "1.19.2"))
        self.label_22.setText(_translate("MainWindow", "Login Message"))
        self.label_23.setText(_translate("MainWindow", "Left Message"))
        self.spawn_btn.setToolTip(_translate("MainWindow", "Start"))
        self.spawn_btn.setText(_translate("MainWindow", "Spawn"))
        self.quit_btn.setToolTip(_translate("MainWindow", "Kick all bot in server"))
        self.quit_btn.setText(_translate("MainWindow", "Quit"))
        self.chatlog_gr.setTitle(_translate("MainWindow", "Chat"))
        self.chat_btn.setToolTip(_translate("MainWindow", "Start"))
        self.chat_btn.setText(_translate("MainWindow", "Chat"))
        self.logbot_gr.setTitle(_translate("MainWindow", "LogBot"))
        self.start_btn.setToolTip(_translate("MainWindow", "Start"))
        self.stop_btn.setToolTip(_translate("MainWindow", "Stop"))
        self.kick_btn_2.setToolTip(_translate("MainWindow", "Kick all bot in server"))
        self.mini_btn.setToolTip(_translate("MainWindow", "Minimized"))
        self.max_btn.setToolTip(_translate("MainWindow", "Maximized"))
        self.close_btn.setToolTip(_translate("MainWindow", "Close"))
import resource.modern


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
